import { NextApiRequest, NextApiResponse } from "next";

export default function (req: NextApiRequest, res: NextApiResponse) {
    res.json([
        {
            table: "add & modify customer",
            items: [
                {
                    idNumber: "8765432",
                    class: "owner",
                    name: { first: "Juan", middle: "Ramos", last: "Dela Cruz" },
                    coOwner: {
                        first: "Juanna",
                        middle: "Ramos",
                        last: "Dela Cruz",
                    },
                    companyName: "Clear Appeal Inc.",
                    tinNo: "123-748-414-5656",
                    registeredAddress: "Pasay City",
                    mailingAddress: "Binondo, Manila ",
                    contactName: "Juan",
                    contactNumber: "099999999",
                    email: "juan@gmail.com",
                    citizenship: "Filipino",
                },
                {
                    idNumber: "8765433",
                    class: "owner",
                    name: { first: "Jane", middle: "", last: "Doe" },
                    coOwner: {
                        first: "Juanna",
                        middle: "Ramos",
                        last: "Dela Cruz",
                    },
                    companyName: "Smarty Life Corp.",
                    tinNo: "156-554-009-23212",
                    registeredAddress: "San Francisco",
                    mailingAddress: "San Francisco",
                    contactName: "Jane",
                    contactNumber: "0951552399",
                    email: "jane@yahoo.com",
                    citizenship: "American",
                },
                {
                    idNumber: "8765434",
                    class: "owner",
                    name: {
                        first: "Chitoge",
                        middle: "Raku",
                        last: "Kirisaki",
                    },
                    coOwner: {
                        first: "Hohenheimn",
                        middle: "Al",
                        last: "Elric",
                    },
                    companyName: "Hitachi",
                    tinNo: "432-565-112-23556",
                    registeredAddress: "Tokyo",
                    mailingAddress: "Mt. Fuji",
                    contactName: "Chitoge",
                    contactNumber: "09515532774",
                    email: "chitogeKirisaki@gmail.com",
                    citizenship: "Japanese",
                },
                {
                    idNumber: "8765435",
                    class: "owner",
                    name: {
                        first: "Christian",
                        middle: "Elano",
                        last: "Black",
                    },
                    coOwner: {
                        first: "Shane",
                        middle: "Elano",
                        last: "Black",
                    },
                    companyName: "Toyota Motor",
                    tinNo: "767-222-2323-1123",
                    registeredAddress: "Pasay City",
                    mailingAddress: "San Francisco ",
                    contactName: "Christian",
                    contactNumber: "099999999",
                    email: "you@no.com",
                    citizenship: "Filipino",
                },
            ],
        },
        {
            table: "add & modify property",
            items: [
                {
                    idNumber: "8765432",
                    unitCode: "2p-168",
                    project: "Bay Garden",
                    address: "Pasay City",
                    developer: "Federal",
                    tower: "Banya tree",
                    floor: "2nd Floor",
                    area: "12.50",
                    class: "Common",
                    type: "Parking",
                    acceptance: "1/16/2015",
                    turnover: "N/A",
                    cutOff: "25th Day of the Month",
                    dueDate: "10th Day of the month",
                    createdAt: "lorem ipsum",
                    updatedAt: "lorem ipsum",
                    createdBy: "lorem ipsum",
                    updatedBy: "lorem ipsum",
                },
                {
                    idNumber: "8765432",
                    unitCode: "RP-3F",
                    project: "Shore Residence",
                    address: "GMA Cavite",
                    developer: "Federal",
                    tower: "Banya tree 2",
                    floor: "3rd Floor",
                    area: "15.50",
                    class: "Common",
                    type: "Parking",
                    acceptance: "1/18/2016",
                    turnover: "N/A",
                    cutOff: "18th Day of the Month",
                    dueDate: "14th Day of the month",
                    createdAt: "lorem ipsum",
                    updatedAt: "lorem ipsum",
                    createdBy: "lorem ipsum",
                    updatedBy: "lorem ipsum",
                },
                {
                    idNumber: "8765432",
                    unitCode: "QW-12",
                    project: "Black Desert",
                    address: "Binan Laguna",
                    developer: "Federal",
                    tower: "Banya tree 2",
                    floor: "5th Floor",
                    area: "10.00",
                    class: "Premium",
                    type: "House",
                    acceptance: "1/15/2019",
                    turnover: "N/A",
                    cutOff: "25th Day of the Month",
                    dueDate: "10th Day of the month",
                    createdAt: "lorem ipsum",
                    updatedAt: "lorem ipsum",
                    createdBy: "lorem ipsum",
                    updatedBy: "lorem ipsum",
                },
                {
                    idNumber: "8765433",
                    unitCode: "QW-34",
                    project: "FinLand",
                    address: "Sky High",
                    developer: "Federal",
                    tower: "Sky Tower 1",
                    floor: "5th Floor",
                    area: "20.00",
                    class: "Premium",
                    type: "Building",
                    acceptance: "1/15/2019",
                    turnover: "N/A",
                    cutOff: "4th Day of the Month",
                    dueDate: "5th Day of the month",
                    createdAt: "lorem ipsum",
                    updatedAt: "lorem ipsum",
                    createdBy: "lorem ipsum",
                    updatedBy: "lorem ipsum",
                },
                {
                    idNumber: "8765433",
                    unitCode: "ER-56",
                    project: "True Damge",
                    address: "Riot Place",
                    developer: "Riot Inc.",
                    tower: "Spiral BG",
                    floor: "15th Floor",
                    area: "50.00",
                    class: "Premium",
                    type: "Company Building",
                    acceptance: "1/15/2019",
                    turnover: "N/A",
                    cutOff: "15th Day of the Month",
                    dueDate: "1st Day of the month",
                    createdAt: "lorem ipsum",
                    updatedAt: "lorem ipsum",
                    createdBy: "lorem ipsum",
                    updatedBy: "lorem ipsum",
                },
                {
                    idNumber: "8765434",
                    unitCode: "TY-67",
                    project: "Yaeger Hunter",
                    address: "Silang Cavite",
                    developer: "Yeager Inc",
                    tower: "Spiral BG",
                    floor: "5th Floor",
                    area: "10.00",
                    class: "Common",
                    type: "Houese",
                    acceptance: "1/15/2019",
                    turnover: "N/A",
                    cutOff: "23rd Day of the Month",
                    dueDate: "10th Day of the month",
                    createdAt: "lorem ipsum",
                    updatedAt: "lorem ipsum",
                    createdBy: "lorem ipsum",
                    updatedBy: "lorem ipsum",
                },
                {
                    idNumber: "8765434",
                    unitCode: "GH-67",
                    project: "The Black",
                    address: "GMA Cavite",
                    developer: "Netflix",
                    tower: "Netflix Tower",
                    floor: "5th Floor",
                    area: "25.00",
                    class: "Premium",
                    type: "Company Building",
                    acceptance: "1/15/2019",
                    turnover: "N/A",
                    cutOff: "25th Day of the Month",
                    dueDate: "10th Day of the month",
                    createdAt: "lorem ipsum",
                    updatedAt: "lorem ipsum",
                    createdBy: "lorem ipsum",
                    updatedBy: "lorem ipsum",
                },
                {
                    idNumber: "8765434",
                    unitCode: "ZX-55",
                    project: "Higher Level",
                    address: "GMA Cavite",
                    developer: "Federal",
                    tower: "Banya tree",
                    floor: "4th Floor",
                    area: "10.00",
                    class: "Common",
                    type: "Gym",
                    acceptance: "1/15/2019",
                    turnover: "N/A",
                    cutOff: "25th Day of the Month",
                    dueDate: "10th Day of the month",
                    createdAt: "lorem ipsum",
                    updatedAt: "lorem ipsum",
                    createdBy: "lorem ipsum",
                    updatedBy: "lorem ipsum",
                },
                {
                    idNumber: "8765435",
                    unitCode: "YU-5E",
                    project: "BRETZ",
                    address: "GMA Cavite",
                    developer: "Federal",
                    tower: "N/A",
                    floor: "1st Floor",
                    area: "10.00",
                    class: "Common",
                    type: "Gym",
                    acceptance: "1/15/2019",
                    turnover: "N/A",
                    cutOff: "25th Day of the Month",
                    dueDate: "10th Day of the month",
                    createdAt: "lorem ipsum",
                    updatedAt: "lorem ipsum",
                    createdBy: "lorem ipsum",
                    updatedBy: "lorem ipsum",
                },
                {
                    idNumber: "8765435",
                    unitCode: "KL-78",
                    project: "Stylish",
                    address: "GMA Cavite",
                    developer: "Youtube",
                    tower: "YT TOWER",
                    floor: "5th Floor",
                    area: "15.00",
                    class: "Premium",
                    type: "Company Building",
                    acceptance: "1/15/2019",
                    turnover: "N/A",
                    cutOff: "25th Day of the Month",
                    dueDate: "10th Day of the month",
                    createdAt: "lorem ipsum",
                    updatedAt: "lorem ipsum",
                    createdBy: "lorem ipsum",
                    updatedBy: "lorem ipsum",
                },
            ],
        },
    ]);
}
