import { NextApiRequest, NextApiResponse } from "next";

export default function (req: NextApiRequest, res: NextApiResponse) {
    res.json([
        {
            table: "admin review",
            items: [
                {
                    id: 1,
                    client: "Tony Start",
                    property: "Avenger Base",
                    tower: "Avenger Tower",
                    type: "Building",
                    requestTime: "Random",
                    item: "Mark 1",
                    quantity: "1",
                    dateTime: "01/01/2001",
                    deliveryPullOut: "2nd Floor",
                    courierName: "Federal",
                    purposes: "Suit",
                },
                {
                    id: 2,
                    client: "Thor Odinson",
                    property: "Mjolnir",
                    tower: "Asgard Tower",
                    type: "Hammer",
                    requestTime: "Random",
                    item: "Mjolnir",
                    quantity: "1",
                    dateTime: "01/01/2001",
                    deliveryPullOut: "2nd Floor",
                    courierName: "Thor",
                    purposes: "Weapon",
                },
                {
                    id: 3,
                    client: "Steve Rogers",
                    property: "Shield",
                    tower: "Shield Tower",
                    type: "Vibranium",
                    requestTime: "Random",
                    item: "Shield",
                    quantity: "1",
                    dateTime: "01/01/2001",
                    deliveryPullOut: "2nd Floor",
                    courierName: "Federal",
                    purposes: "Weapon",
                },
                {
                    id: 4,
                    client: "Natasha Romanoff",
                    property: "Black Widow",
                    tower: "Shield Tower",
                    type: "Agent",
                    requestTime: "Random",
                    item: "Black Suit",
                    quantity: "Federal",
                    dateTime: "01/01/2001",
                    deliveryPullOut: "2nd Floor",
                    courierName: "Federal",
                    purposes: "Agent",
                },
            ],
        },
        {
            table: "manage approval",
            items: [
                {
                    id: 1,
                    client: "Peter Parker",
                    property: "Spider Mask",
                    tower: "N/A",
                    type: "Hero",
                    requestTime: "Random",
                    item: "Web",
                    quantity: "1",
                    dateTime: "01/01/2001",
                    deliveryPullOut: "2nd Floor",
                    courierName: "Federal",
                    purposes: "Hero",
                },
                {
                    id: 2,
                    client: "Steven Strange",
                    property: "Cape",
                    tower: "Sanctum Sanctorum",
                    type: "Sorcerer",
                    requestTime: "Random",
                    item: "Magic",
                    quantity: "1",
                    dateTime: "01/01/2001",
                    deliveryPullOut: "2nd Floor",
                    courierName: "Federal",
                    purposes: "Hero",
                },
                {
                    id: 3,
                    client: "T'Challa",
                    property: "Black Panther",
                    tower: "Wakanda",
                    type: "Hero",
                    requestTime: "Random",
                    item: "Panther",
                    quantity: "1",
                    dateTime: "01/01/2001",
                    deliveryPullOut: "2nd Floor",
                    courierName: "Federal",
                    purposes: "King",
                },
                {
                    id: 4,
                    client: "Bruce Banner",
                    property: "Hulk",
                    tower: "Avenger Tower",
                    type: "Sciencetist",
                    requestTime: "random",
                    item: "Gamma",
                    quantity: "1",
                    dateTime: "01/01/2001",
                    deliveryPullOut: "2nd Floor",
                    courierName: "Federal",
                    purposes: "Hero",
                },
            ],
        },
        {},
    ]);
}
